spring:
  application:
    name: order-service-gk
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.43.73:9411/

server:
  port: 4040

eureka:
  client:
    service-url:
      defaultZone: http://192.168.43.73:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: order-service-gk

logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug