spring:
  application:
    name: order-service-gk
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://34.194.217.116:9411/
  rabbitmq:
    host: 34.194.217.116
    port: 5672
    username: amqpuser
    password: p@ssw0rd123

server:
  port: 4040

eureka:
  client:
    service-url:
      defaultZone: http://34.194.217.116:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: order-service-gk

logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug