spring:
  application:
    name: product-service-gk
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://34.237.212.57:9411/
  rabbitmq:
    host: 34.194.217.116
    port: 5672
    username: amqpuser
    password: p@ssw0rd123


server:
  port: 2020

eureka:
  client:
    service-url:
      #default-zone: http://169.254.143.146:8761/eureka
      defaultZone: http://34.233.195.223:8761/eureka
  instance:
    hostname: product-service-gk
    prefer-ip-address: false

logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug