spring:
  application:
    name: product-service-gk
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://10.10.181.7:9411/
  rabbitmq:
    host: 10.10.181.7
    port: 5672
    username: guest
    password: guest


server:
  port: 2020

eureka:
  client:
    service-url:
      #default-zone: http://169.254.143.146:8761/eureka
      defaultZone: http://10.10.181.7:8761/eureka
  instance:
    hostname: product-service-gk
    prefer-ip-address: false

logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug